# Generated by Django 4.2.5 on 2023-12-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynewsite', '0002_postcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_counter',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
